### ISSUE TITLE
Is this working for Linux?

### ISSUE THREAD

**Issue by drpaneas** [David-H-Bolton/LearnC#1]
Hello,

I am interested in buying the book and going down the C Programming with Games. However I have noticed you mention Windows only. Can this be the code is not compatible for Mac or Linux?

Thanks,
Panos

**Comment by David-H-Bolton** [comment]
Hi  Panos
That book is for Windows though the source code for Linux doesn't vary that
much. I did the conversion about three years ago and put the Linux code on
GitHub. It's in https://github.com/David-H-Bolton/LearnCOnLinux    The
chapter 48 is the full source code.of the game.

The main differences between the Windows (VS code) and Linux (Gcc or Clang)
is that the path to SDL2 libraries on Linux have a SDL prefix so instead of
SDL.h it's SDL\SDL.h . Also Visual Studio expect the safe str functions
strcmp_s etc  while the clang one doesn't. The vs code JSON files are also
probably out of date as the clang version will be higher than the one I
used.

I am working on a 2nd book which will be Linux but Raspberry Pi oriented
with three games in it- Asteroids, a Match Three game and possibly a Tower
Defence game.  But it's at least 6 months away.

I hope that helps!

Cheers

David

**Comment by drpaneas** [comment]
Excellent, thx David
